// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.2.1")]
[assembly: AssemblyFileVersionAttribute("1.2.1")]
[assembly: AssemblyInformationalVersionAttribute("1.2.1 54d9e7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.1";
    }
}
