// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Meerkat Security HMAC")]
[assembly: AssemblyCopyrightAttribute("� 2016 Paul Hatcher")]
[assembly: AssemblyVersionAttribute("2.1.1")]
[assembly: AssemblyFileVersionAttribute("2.1.1")]
[assembly: AssemblyInformationalVersionAttribute("2.1.1 bf02fa")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.1.1";
    }
}
